apiVersion: v2
name: myapp
description: A Helm chart for Maven Hello World application
type: application
version: 0.1.0
appVersion: "1.0.1"
maintainers:
  - name: Guy Aloosh
    email: guyaloosh@example.com

